name: lakehouse
version: "1.0.0"
config-version: 2
profile: lakehouse

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  lakehouse:
    staging:
      +materialized: table
    marts:
      +materialized: table
      +table_type: iceberg
      +format: parquet
